[package]
name = "rust-inferential-statistics"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
ndarray = "0.16.1"
ndarray-stats = "0.6.0"
serde = { version = "*", features = ["derive"] }
statrs = "0.18.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
